### PR TITLE
Fix: Unable to replay when status is stopped

### PR DESCRIPTION
**Pull request by Virczz**
Fixed not working if trying to replay when playback state is stopped.

### CODE REVIEW

**Comment by flowkscai** [comment]
Is there a maintainer who can help review this PR?

**Comment by illia-romanenko** [comment]
Hey 👋, Since it's marked as Draft - we didn't check it yet. If it's ready for review - can we please update it and make not Draft?

**Comment by flowkscai** [comment]
> Hey 👋, Since it's marked as Draft - we didn't check it yet. If it's ready for review - can we please update it and make not Draft?

My apologies, didn't notice this. Many thanks for the prompt reply.

**Review by illia-romanenko — APPROVED** [review]
LGTM

**Comment by The-Shahin** [comment]
It is not fixed; I encountered this problem again. Additionally, when I try to play a video on the iOS simulator, the app crashes. The main problem with the player is that the controller is not initializing properly. When I try to call initialize(), I get a "lateInitialization error."

**Comment by flowkscai** [comment]
> It is not fixed; I encountered this problem again. Additionally, when I try to play a video on the iOS simulator, the app crashes. The main problem with the player is that the controller is not initializing properly. When I try to call initialize(), I get a "lateInitialization error."

Not related to this issue, you should open a new one.

**Pull request merged**
