### PR TITLE
add vlc options from flutter

### PR DESCRIPTION
**Pull request by pharshdev**
i think it would be nice to have this.

### CODE REVIEW

**Comment by solid-software** [comment]
Nice 👍 thanks for your contribution @pharshdev! 

Is there a way you can remove "System.out.println" - so we can have more clean console for users + update changeling.md to include this new version changes? 
Also should we add same options for iOS part?

@mitchross if you have time - could you please take a look and let us know what you think about it?

**Comment by mitchross** [comment]
I will review.

**Comment by alr2413** [comment]
ping @solid-software 
When will you merge it?

**Comment by alr2413** [comment]
ping @pharshdev.

Please resolve the mentioned conflicts.
Thanks.

**Comment by mitchross** [comment]
If @pharshdev doesnt take care of this, ill fork and take care of it this week.

**Comment by mitchross** [comment]
Fix for this PR https://github.com/solid-software/flutter_vlc_player/pull/84

**Pull request closed without merging**
