### PR TITLE
support playback local file and add more helper methods for player 

### PR DESCRIPTION
**Pull request by chinshou**
Only implemented and tested on Android. IOS support will be added later

### CODE REVIEW

**Comment by solid-software** [comment]
Hi @chinshou - thanks for your contribution! 

Let us know when iOS is ready so we can merge that altogether.

**Comment by chinshou** [comment]
> Hi @chinshou - thanks for your contribution!
> 
> Let us know when iOS is ready so we can merge that altogether.

OK, I will start support ios this weekend. And will ask for review when it is ready

**Comment by chinshou** [comment]
I tested on IOS without find some problem. Maybe someone can review my changes now.

**Comment by chinshou** [comment]
I tested on IOS without find some problem. Maybe someone can review my changes now. @solid-software

**Comment by solid-software** [comment]
Thanks @chinshou, we've completed migration to swift and and it looks like there are some conflicts - could you please resolve them first?

**Comment by chinshou** [comment]
> Thanks @chinshou, we've completed migration to swift and and it looks like there are some conflicts - could you please resolve them first?

Hello,

I noticed that the 3.0 release completely switch to swift, I am not familar with swift , so I need sometime to figure out how to support swift.

**Comment by solid-software** [comment]
Great, thanks @chinshou !

**Comment by topilski** [comment]
Hello, is this PR will be merged?

**Comment by chinshou** [comment]
> Hello, is this PR will be merged?

sorry, the ios part code still stay at objective-c, but I am busy recently, and can not find some time to port it to swift yet.

**Comment by dhruvkelawala** [comment]
I am facing this error logs after using these commits and @chinshou 's repo 

`E/VLC     ( 3565): [0000007db1aad790/12ad] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d181b9e10/130a] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d181b9e10/130a] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d17e6ac90/12ae] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ae] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/130b] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/130b] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11c09c90/12af] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12af] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d181b9e10/130c] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d181b9e10/130c] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d181c2d90/12b0] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12b0] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/130d] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/130d] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d34b51b90/12ab] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ab] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/130e] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/130e] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d33bc2890/12ac] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ac] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/1311] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/1311] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d33bcf090/12ad] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ad] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d202b5f10/1312] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d202b5f10/1312] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d17e6ac90/12ae] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ae] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/1313] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/1313] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11c09c90/12af] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12af] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d202b6190/1314] libvlc window: request 1 not implemented
I/flutter ( 3565): PlayingState.PLAYING
E/VLC     ( 3565): [0000007d202b6190/1314] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d181c2d90/12b0] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12b0] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/1315] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/1315] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d34b51b90/12ab] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ab] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/1317] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/1317] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d33bc2890/12ac] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ac] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/131a] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/131a] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d33bcf090/12ad] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ad] libvlc decoder: failed to create video output
I/flutter ( 3565): PlayingState.PLAYING
E/VLC     ( 3565): [0000007d202b6410/131b] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d202b6410/131b] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d17e6ac90/12ae] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ae] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/131c] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/131c] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11c09c90/12af] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12af] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d202b6690/131d] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d202b6690/131d] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d181c2d90/12b0] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12b0] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/131e] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/131e] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d34b51b90/12ab] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ab] libvlc decoder: failed to create video output
E/VLC     ( 3565): [0000007d11cc6090/131f] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d11cc6090/131f] libvlc window: request 1 not implemented
E/VLC     ( 3565): [0000007d33bc2890/12ac] libvlc video output: video output creation failed
E/VLC     ( 3565): [0000007db1aad790/12ac] libvlc decoder: failed to create video output
I/flutter ( 3565): PlayingState.STOPPED`

**Comment by dhruvkelawala** [comment]
But I hope subtitle support is added soon

**Comment by mitchross** [comment]
This change will break flutter vlc player. The change needs to be done on swift.

**Comment by solid-software** [comment]
If somebody wants to add the missing iOS part, please let us know. As there was no movement for quite a while - I'm closing this for now.

**Pull request closed without merging**
