### PR TITLE
Vlckit SDK updates and cleanup

### PR DESCRIPTION
**Pull request by mitchross**
Migrate to latest VLC Kit SDK's. Cleanup example build configs. Confirmed building on xcode 12 and big sur.

### CODE REVIEW

**Comment by solid-pavloprykhodko** [comment]
I have tested this update and found that VlcPlayer throws an error on iOS after building with Flutter in debug mode with message: MissingPluginException (MissingPluginException(No implementation found for method dispose on channel flutter_video_plugin/getVideoView_0))

Also it shows an error in no-debug mode as in the attached file:
Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-24 at 19 06 12

It was tested on iOS 14.0, Xcode 12, flutter 1.22.4

**Comment by mitchross** [comment]
@solid-pavloprykhodko can you send me the exact command you ran? Also which OS? I'll try rebuilding on another Macbook of mine.

**Comment by mitchross** [comment]
@solid-pavloprykhodko i built on a entirely separate macbook with no issues.

Few things to try

$ Flutter upgrade

$ pod repo update

in the example project directory run
$ Flutter clean

**Comment by solid-pavloprykhodko** [comment]
@mitchross I tested on flutter 1.22.4, iOS 13.2.2 and iOS 14.0. I ran with flutter run and in debug mode.
I also have local changes in main.dart to test behaviour with deleting and recreating VlcPlayer and noticed that without these changes bugs do not occur:

class _MyAppState extends State<MyApp> {
  final GlobalKey<NavigatorState> _navigator = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: _navigator,
      initialRoute: '/',
      routes: <String, WidgetBuilder>{
        '/': (context) => Scaffold(
              body: Center(
                child: RaisedButton(onPressed: () {
                  Navigator.of(context).push(
                      MaterialPageRoute(builder: (context) => MyAppScaffold()));
                }),
              ),
            ),
      },
    );
  }
}

I think it may be not connected with your changes, because I tried with different flutter versions and also on flutter_vlc_player master branch and these bugs also occur with local changes in main.dart

**Comment by solid-pavloprykhodko** [comment]
@mitchross Yes, these bugs are not related to your changes, I'm sorry. It is safe to merge.

**Comment by solid-software** [comment]
Thanks @mitchross @solid-pavloprykhodko. We want to collect a little bit more changes for 4.0.3 before releasing - so stay tuned.

**Comment by mitchross** [comment]
@solid-software no worries

**Pull request merged**
