### PR TITLE
Replace List.forEach to for-loop (#288).

### PR DESCRIPTION
**Pull request by kostov**
Seems like List.forEach is not supported on old Android versions.

### CODE REVIEW

**Review by MahmoudQassass — APPROVED** [review]

**Review by illia-romanenko — COMMENTED** [review]
Hey thanks! Do you mind also adding Changelog & new version so we can quickly release it and properly credit your contribution?

**Comment by kostov** [comment]
Sorry, this is my first change on github. Please tell me what exactly should I do?

**Comment by kostov** [comment]
Should I just modify CHANGELOG.md with:

## 7.0.2
* Fixed work on Android 6-.
Credits to Yury Kostov (https://github.com/kostov).

Is that all?

**Comment by kostov** [comment]
Hi, all, I recently discovered and fixed another bug under Android: if you close the application using the system Back button, and then return to the application, the player no longer works.
```
flutter_vlc_player/android/src/main/java/software/solid/fluttervlcplayer/FlutterVlcPlayerPlugin.java 
in method onAttachedToActivity(@NonNull Activity Plugin Binding binding) {
        if (flutter Vlc Player Factory == null) // here
```
If you comment out this line and create a factory unconditionally (and then do flutterPluginBinding), then the player starts working again. Perhaps you don't need to create the factory if it already exists, but you still need to do binding - I haven't figured it out yet, because I don't have the necessary knowledge.

**Comment by solid-software** [comment]
Hey, yes - sorry for the delay. As you know we are a bit busy with Russian invasion of Ukraine so we'll need a bit more time. Proposed Changeling updates looks good - please add them to the PR.

**Review by solid-software — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
