### PR TITLE
Add Function to Change/ADD subtitle and change the audio track 

### PR DESCRIPTION
**Pull request by rikaweb**
Add Function to Change/ADD subtitle and change the audio track

### CODE REVIEW

**Comment by alr2413** [comment]
Hi,

Is it possible to return the name or text of audios & subtitles list in addition to the index?

Thanks.

**Comment by solid-software** [comment]
Great job, thanks for the PR @rikaweb!

Do you plan on adding iOS part for it?

**Comment by rikaweb** [comment]
Hi
@solid-software  I just update it for android and test it on android,  I am java developer and have no preference on ios. maybe we can publish it and ask the IOS developer to help.

**Comment by solid-software** [comment]
As we declare support for both mobile platforms (Android and iOS) I think it would be hard to merge without adding iOS part to it. Let's see if somebody can help here to add iOS part of it so we can merge.

**Comment by rikaweb** [comment]
> Hi,
> 
> Is it possible to return the name or text of audios & subtitles list in addition to the index?
> 
> Thanks.

HI @alr2413 
The VLC use this function for  audio and subtitle description :
    /**
     * Get the list of available SPU (subtitle and audio tracks).
     */
    public TrackDescription[] getSpuTracks() {
        return nativeGetSpuTracks();
    }
So this method in 'FlutterVideoView.java' file can provide what you are searching for
https://stackoverflow.com/questions/48976386/libvlc-how-do-i-know-if-subtitles-text-track-are-external-or-part-of-video-co

Thanks

**Comment by mitchross** [comment]
@solid-software I can do iOS part this week.... Is it possible to change this PR to a new feature branch on solid software repo? Forking a fork is really painful. If we make a new branch on solid software called, "feature/audio-track" , merge this PR into that branch, then I will fork the solid software repo, add in iOS. Finally we can PR the feature/audio branch to master.

**Comment by solid-software** [comment]
What if @rikaweb adds you to rikaweb:master so you can make the changes here? I think that might simplify it a bit.

**Comment by alr2413** [comment]
I think, it's better to have a dev-branch beside master branch for developing purpose.

**Comment by rikaweb** [comment]
> What if @rikaweb adds you to rikaweb:master so you can make the changes here? I think that might simplify it a bit.

I can do that if needed!

**Comment by mitchross** [comment]
> > What if @rikaweb adds you to rikaweb:master so you can make the changes here? I think that might simplify it a bit.
> 
> I can do that if needed!

Add me to your master, I'll make iOS changes

**Comment by rikaweb** [comment]
> > > What if @rikaweb adds you to rikaweb:master so you can make the changes here? I think that might simplify it a bit.
> > 
> > 
> > I can do that if needed!
> 
> Add me to your master, I'll make iOS changes

Added!

**Comment by mitchross** [comment]
@rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?

**Comment by rikaweb** [comment]
> @rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?

I add subtitles to video first and then test the change subtitle option.

**Comment by mitchross** [comment]
> > @rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?
> 
> I add subtitles to video first and then test the change subtitle option.

Can you please provide specific instructions step by step? Local video? hosted video ? what code are you using to add subtitles? If you can provide me with this,  I can do the ios code.

**Comment by rikaweb** [comment]
> > > @rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?
> > 
> > 
> > I add subtitles to video first and then test the change subtitle option.
> 
> Can you please provide specific instructions step by step? Local video? hosted video ? what code are you using to add subtitles? If you can provide me with this, I can do the ios code.

Please send me your email, I send the file to you in private

**Comment by mitchross** [comment]
> > > > @rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?
> > > 
> > > 
> > > I add subtitles to video first and then test the change subtitle option.
> > 
> > 
> > Can you please provide specific instructions step by step? Local video? hosted video ? what code are you using to add subtitles? If you can provide me with this, I can do the ios code.
> 
> Please send me your email, I send the file to you in private

perfect.... mitchross09@gmail.com

**Comment by rikaweb** [comment]
> > > > > @rikaweb I need a video file to test this with thats hosted online. How did you test your android changes?
> > > > 
> > > > 
> > > > I add subtitles to video first and then test the change subtitle option.
> > > 
> > > 
> > > Can you please provide specific instructions step by step? Local video? hosted video ? what code are you using to add subtitles? If you can provide me with this, I can do the ios code.
> > 
> > 
> > Please send me your email, I send the file to you in private
> 
> perfect.... [mitchross09@gmail.com](mailto:mitchross09@gmail.com)

Sent!

**Comment by mitchross** [comment]
@rikaweb iOS changes implemented

**Comment by dhruvkelawala** [comment]
I have this changes are merged soon in the package and published. Thanks @rikaweb @mitchross

**Comment by solid-software** [comment]
Great job - thanks @rikaweb @mitchross !

**Comment by dhruvkelawala** [comment]
How add a subtitle file (.srt) from network? @rikaweb @mitchross @solid-software

**Comment by rikaweb** [comment]
> How add a subtitle file (.srt) from network? @rikaweb @mitchross @solid-software

you need first download the file then add it to VLC. VLC doesn't support network subtitles. you can use cache to that too.

**Comment by dhruvkelawala** [comment]
> > How add a subtitle file (.srt) from network? @rikaweb @mitchross @solid-software
> 
> you need first download the file then add it to VLC. VLC doesn't support network subtitles. you can use cache to that too.

Can't we make a helper function? Something like 

```
controller.addSubtitle(Subtitle.fromNetwork(url));

```

Same with Subtitle.fromLocal(path)

**Comment by mitchross** [comment]
> > > How add a subtitle file (.srt) from network? @rikaweb @mitchross @solid-software
> > 
> > 
> > you need first download the file then add it to VLC. VLC doesn't support network subtitles. you can use cache to that too.
> 
> Can't we make a helper function? Something like
> 
> ```
> controller.addSubtitle(Subtitle.fromNetwork(url));
> ```
> 
> Same with Subtitle.fromLocal(path)

submit a PR, I will review

**Comment by alr2413** [comment]
I will submit a new PR and reference these issues there.

**Comment by alr2413** [comment]
> > > > How add a subtitle file (.srt) from network? @rikaweb @mitchross @solid-software
> > > 
> > > 
> > > you need first download the file then add it to VLC. VLC doesn't support network subtitles. you can use cache to that too.
> > 
> > 
> > Can't we make a helper function? Something like
> > ```
> > controller.addSubtitle(Subtitle.fromNetwork(url));
> > ```
> > 
> > 
> > Same with Subtitle.fromLocal(path)
> 
> submit a PR, I will review


> I will submit a new PR and reference these issues there.

@dhruvkelawala , @mitchross 
Here is my PR #104.

**Comment by dhruvkelawala** [comment]
Yes... I saw it. Looks great. It's upto @solid-software and @mitchross to approve it.

**Pull request merged**
