### PR TITLE
Do not dispose controller when its null

### PR DESCRIPTION
**Pull request by Zchandev**

### CODE REVIEW

**Comment by solid-software** [comment]
Hey @Zchandev, thanks for your PR! Could you please describe your use case on how you get controller to be null?

**Comment by Zchandev** [comment]
> Hey @Zchandev, thanks for your PR! Could you please describe your use case on how you get controller to be null?

Hi. I use this plugin for webm playback. Some users of my app complained about gray error screens and videos still playing in the background even after closing. I checked my Crashlytics logs and found that there is an issue with _controller being null on dispose.

I fixed it on my local fork and one of the affected users tested it. He hold me that issue has gone with that fix.

Here is my crashlytics logs

Снимок экрана 2020-10-10 в 23 08 20

**Comment by solid-software** [comment]
Hey @mitchross, can you help us here? I noticed that you added deactivate() - so I want to clarify that this fix will help.

**Comment by mitchross** [comment]
@solid-software this change is safe to merge!

**Comment by solid-software** [comment]
@mitchross ok thanks 🙏 

@Zchandev could you please update CHANGELOG.md and pubspec.yaml with new version/changes description?

**Comment by solid-software** [comment]
@Zchandev @mitchross we plan to go with @solid-pavloprykhodko PR on this - please let us know if you feel other way.

**Pull request closed without merging**
