### PR TITLE
updated flutter_lints

### PR DESCRIPTION
**Pull request by pinpong**
Updated flutter_lint package to be more developer friendly.

### CODE REVIEW

**Comment by mitchross** [comment]
[illia-romanenko](https://github.com/illia-romanenko) you may want to consider a github action to apply lints.

**Comment by solid-oleksandrhordiienko** [comment]
Thanks for PR!

> [illia-romanenko](https://github.com/illia-romanenko) you may want to consider a github action to apply lints.

I will add action soon

**Comment by illia-romanenko** [comment]
Yes, let's start with action first and then we'll switch back to reviewing other PRs.

**Comment by pinpong** [comment]
Seems like this is already solved by https://github.com/solid-software/flutter_vlc_player/pull/403

**Pull request closed without merging**
