### PR TITLE
removed AutomaticKeepAliveClientMixin to fix/prevent unwanted behavior

### PR DESCRIPTION
**Pull request by pinpong**
AutomaticKeepAliveClientMixin was only to fix unwanted behavior of the example app.
This patch includes all necessary fixes for the example.
Maybe that is a breaking change for some projects but keeping alive should be handle on the plugin implementation side.

### CODE REVIEW

**Comment by mitchross** [comment]
If its a breaking change the major version of this repo should be updated.

Do you have a way to test for the breaking change? I run android and ios and can test this for you, given the requirements.

**Comment by pinpong** [comment]
I don't know how other dev implement it but in my case i was wondering why disposed was never called.

**Comment by pinpong** [comment]
The OR is not done yet. The ANR is not fixed in my app. Keep alive was just a method to reduces the symptoms.

**Comment by solid-oleksandrhordiienko** [comment]
Thanks for PR @pinpong!
Nice fix. The fist example, that I found, of what this fix improved. Bug connected with continuing video playing after changing page.

**Comment by pinpong** [comment]
@solid-oleksandrhordiienko ready to merge

**Comment by illia-romanenko** [comment]
@mitchross do you mind checking this one too? I would love also to get a clarity on breaking change. Is it possible or real breaking change?

**Comment by mitchross** [comment]
I dont think it needs a v8 breaking, can roll the minor version. Maybe if it was open source project with millions of users, otherwise, 7.4 is fine imo

**Comment by pinpong** [comment]
Ok

**Pull request merged**
