### PR TITLE
added allowBackgroundPlayback

### PR DESCRIPTION
**Pull request by pinpong**

### CODE REVIEW

**Review by illia-romanenko — COMMENTED** [review]
Thanks for the PR @pinpong!

It looks like you are using some specific formatter or maybe extended line length as it's breaking a bit previous formatting. I can change that but just wanted to check first.

@mitchross do you want to take a look at this one?

**Comment by pinpong** [comment]
Please try `$ dart format .` and let me know if it's format again.

**Comment by mitchross** [comment]
How exactly does this work? Do you mind explaining your changes? Just curious.

**Comment by pinpong** [comment]
The lifeCycleObserver can handle by the devs now. In my case i also want to stop the video if the widget is not visible.

```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.resumed:
        _onVisibilityChanged(true);
        break;
      case AppLifecycleState.detached:
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
        _onVisibilityChanged(false);
    }
    super.didChangeAppLifecycleState(state);
  }

**Comment by solid-oleksandrhordiienko** [comment]
Thanks for PR @pinpong!
Good feature. Tested it, everything works correctly in my case.

**Comment by mitchross** [comment]
@pinpong are you going to resolve the conflicts?

**Comment by pinpong** [comment]
@mitchross ready to merge

**Comment by mitchross** [comment]
Looks good to me

**Comment by illia-romanenko** [comment]
Thanks!

**Pull request merged**
